---
- name: Install requirements
  package:
    name: ["git", "composer"]
    state: present

- name: Check if planning-biblio directories already exists
  stat:
    path: "{{ planning_separate_git_dir }}"
  register: planning_git_dir

- name: Clone Planning-biblio git repository
  git:
    repo: https://github.com/PlanningBiblio/PlanningBiblio.git
    dest: "{{ planning_content_dest }}"
    version: "{{ planning_git_branch_version }}"
    separate_git_dir: "{{ planning_separate_git_dir }}"
    force: true
  when: not planning_git_dir.stat.exists or planning_force_update

- name: Composer update
  composer:
    command: update
    working_dir: "{{ planning_content_dest }}"
  when: not planning_git_dir.stat.exists or planning_force_update

- name: Change Planning Biblio directory owner
  file:
    path: "/var/www/planning"
    owner: "www-data"
    group: "www-data"
    recurse: true

- name: Add GRANT OPTION for mariadb root user.
  mysql_user:
    name: root
    priv: '*.*:ALL,GRANT'
    state: present
  when: not planning_git_dir.stat.exists or planning_force_update
