---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: supertarto.apache
    - role: supertarto.mariadb
    - role: supertarto.php
    - role: supertarto.planning-biblio
  vars:
    php_packages:
      - php7.0
      - php7.0-mysql
      - php7.0-curl
      - php7.0-json
      - php7.0-ldap
      - php7.0-pdo
      - php7.0-xml
    apache_create_vhosts: true
    apache_vhosts_filename: "planning.conf"
    apache_vhost_config:
      - listen_ip: "*"
        listen_port: 80
        server_name: host1
        documentroot: "{{ planning_content_dest }}"
        serveradmin: admin@localhost
        custom_param: |
          ProxyRequests Off
          ProxyPreserveHost On
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
          LogLevel warn
        directory:
          - path: "{{ planning_content_dest }}"
            config: |
              AllowOverride All
              Order deny,allow
              allow from all

    mariadb_use_dump_script: false
    mariadb_databases:
      - name: "PlanningBiblio"
